// Generated by `tools/location` from the publisher's own file. Do not edit by hand;
// regenerate instead. Source: ISO 3166-1 codes from the tz database `iso3166.tab` (public domain); names from Wikidata labels (CC0), queried 2026-09-13.

import type { CountryTable } from './types.js';

export const COUNTRIES: CountryTable = {
	languages: ['en', 'ko', 'ja', 'zh', 'vi', 'es', 'it', 'de', 'ru'],
	table: `
		AD|Andorra|안도라|アンドラ|安道尔|Andorra|Andorra|Andorra|Andorra|Андорра
		AE|United Arab Emirates|아랍에미리트|アラブ首長国連邦|阿拉伯联合酋长国|Các Tiểu vương quốc Ả Rập Thống nhất|Emiratos Árabes Unidos|Emirati Arabi Uniti|Vereinigte Arabische Emirate|Объединённые Арабские Эмираты
		AF|Afghanistan|아프가니스탄|アフガニスタン|阿富汗|Afghanistan|Afganistán|Afghanistan|Afghanistan|Афганистан
		AG|Antigua and Barbuda|앤티가 바부다|アンティグア・バーブーダ|安提瓜和巴布达|Antigua và Barbuda|Antigua y Barbuda|Antigua e Barbuda|Antigua und Barbuda|Антигуа и Барбуда
		AI|Anguilla|앵귈라|アンギラ|安圭拉|Anguilla|Anguila|Anguilla|Anguilla|Ангилья
		AL|Albania|알바니아|アルバニア|阿尔巴尼亚|Albania|Albania|Albania|Albanien|Албания
		AM|Armenia|아르메니아|アルメニア|亚美尼亚|Armenia|Armenia|Armenia|Armenien|Армения
		AO|Angola|앙골라|アンゴラ|安哥拉|Angola|Angola|Angola|Angola|Ангола
		AQ|Antarctica|남극|南極大陸|南极洲|Châu Nam Cực|Antártida|Antartide|Antarktika|Антарктида
		AR|Argentina|아르헨티나|アルゼンチン|阿根廷|Argentina|Argentina|Argentina|Argentinien|Аргентина
		AS|American Samoa|아메리칸사모아|アメリカ領サモア|美属萨摩亚|Samoa thuộc Mỹ|Samoa Americana|Samoa Americane|Amerikanisch-Samoa|Американское Самоа
		AT|Austria|오스트리아|オーストリア|奥地利|Áo|Austria|Austria|Österreich|Австрия
		AU|Australia|오스트레일리아|オーストラリア|澳大利亚|Úc|Australia|Australia|Australien|Австралия
		AW|Aruba|아루바|アルバ|阿鲁巴|Aruba|Aruba|Aruba|Aruba|Аруба
		AX|Åland|올란드 제도|オーランド諸島|奥兰|Åland|Åland|Isole Åland|Åland|Аландские острова
		AZ|Azerbaijan|아제르바이잔|アゼルバイジャン|阿塞拜疆|Azerbaijan|Azerbaiyán|Azerbaigian|Aserbaidschan|Азербайджан
		BA|Bosnia and Herzegovina|보스니아 헤르체고비나|ボスニア・ヘルツェゴビナ|波斯尼亚和黑塞哥维那|Bosna và Hercegovina|Bosnia y Herzegovina|Bosnia ed Erzegovina|Bosnien und Herzegowina|Босния и Герцеговина
		BB|Barbados|바베이도스|バルバドス|巴巴多斯|Barbados|Barbados|Barbados|Barbados|Барбадос
		BD|Bangladesh|방글라데시|バングラデシュ|孟加拉国|Bangladesh|Bangladés|Bangladesh|Bangladesch|Бангладеш
		BE|Belgium|벨기에|ベルギー|比利时|Bỉ|Bélgica|Belgio|Belgien|Бельгия
		BF|Burkina Faso|부르키나파소|ブルキナファソ|布基纳法索|Burkina Faso|Burkina Faso|Burkina Faso|Burkina Faso|Буркина-Фасо
		BG|Bulgaria|불가리아|ブルガリア|保加利亚|Bulgaria|Bulgaria|Bulgaria|Bulgarien|Болгария
		BH|Bahrain|바레인|バーレーン|巴林|Bahrain|Baréin|Bahrein|Bahrain|Бахрейн
		BI|Burundi|부룬디|ブルンジ|布隆迪|Burundi|Burundi|Burundi|Burundi|Бурунди
		BJ|Benin|베냉|ベナン|贝宁|Bénin|Benín|Benin|Benin|Бенин
		BL|Saint Barthélemy|생바르텔레미|サン・バルテルミー島|圣巴泰勒米|Saint-Barthélemy|San Bartolomé|Saint-Barthélemy|Saint-Barthélemy|Сен-Бартелеми
		BM|Bermuda|버뮤다|バミューダ|百慕大|Bermuda|Bermudas|Bermuda|Bermuda|Бермудские Острова
		BN|Brunei|브루나이|ブルネイ|文莱|Brunei|Brunéi|Brunei|Brunei|Бруней
		BO|Bolivia|볼리비아|ボリビア|玻利维亚|Bolivia|Bolivia|Bolivia|Bolivien|Боливия
		BQ|Caribbean Netherlands|카리브 네덜란드|ボネール、シント・ユースタティウスおよびサバ|荷兰加勒比区|Caribe Hà Lan|Caribe neerlandés|Paesi Bassi caraibici|Karibische Niederlande|Бонайре, Синт-Эстатиус и Саба
		BR|Brazil|브라질|ブラジル|巴西|Brasil|Brasil|Brasile|Brasilien|Бразилия
		BS|The Bahamas|바하마|バハマ|巴哈马|Bahamas|Bahamas|Bahamas|Bahamas|Багамские Острова
		BT|Bhutan|부탄|ブータン|不丹|Bhutan|Bután|Bhutan|Bhutan|Бутан
		BV|Bouvet Island|부베섬|ブーベ島|布韦岛|Đảo Bouvet|Isla Bouvet|Isola Bouvet|Bouvetinsel|Остров Буве
		BW|Botswana|보츠와나|ボツワナ|博茨瓦纳|Botswana|Botsuana|Botswana|Botswana|Ботсвана
		BY|Belarus|벨라루스|ベラルーシ|白俄罗斯|Belarus|Bielorrusia|Bielorussia|Belarus|Беларусь
		BZ|Belize|벨리즈|ベリーズ|伯利兹|Belize|Belice|Belize|Belize|Белиз
		CA|Canada|캐나다|カナダ|加拿大|Canada|Canadá|Canada|Kanada|Канада
		CC|Cocos (Keeling) Islands|코코스 제도|ココス諸島|科科斯（基林）群岛|Quần đảo Cocos (Keeling)|Islas Cocos|Isole Cocos|Kokosinseln|Кокосовые острова
		CD|Democratic Republic of the Congo|콩고 민주 공화국|コンゴ民主共和国|刚果民主共和国|Cộng hòa Dân chủ Congo|República Democrática del Congo|Repubblica Democratica del Congo|Demokratische Republik Kongo|Демократическая Республика Конго
		CF|Central African Republic|중앙아프리카 공화국|中央アフリカ共和国|中非共和国|Cộng hòa Trung Phi|República Centroafricana|Repubblica Centrafricana|Zentralafrikanische Republik|Центральноафриканская Республика
		CG|Republic of the Congo|콩고 공화국|コンゴ共和国|刚果共和国|Cộng hòa Congo|Congo|Repubblica del Congo|Republik Kongo|Республика Конго
		CH|Switzerland|스위스|スイス|瑞士|Thụy Sĩ|Suiza|Svizzera|Schweiz|Швейцария
		CI|Ivory Coast|코트디부아르|コートジボワール|科特迪瓦|Bờ Biển Ngà|Costa de Marfil|Costa d'Avorio|Elfenbeinküste|Кот-д’Ивуар
		CK|Cook Islands|쿡 제도|クック諸島|库克群岛|Quần đảo Cook|Islas Cook|Isole Cook|Cookinseln|Острова Кука
		CL|Chile|칠레|チリ|智利|Chile|Chile|Cile|Chile|Чили
		CM|Cameroon|카메룬|カメルーン|喀麦隆|Cameroon|Camerún|Camerun|Kamerun|Камерун
		CN|People's Republic of China|중화인민공화국|中華人民共和国|中华人民共和国|Trung Quốc|República Popular China|Cina|Volksrepublik China|Китай
		CO|Colombia|콜롬비아|コロンビア|哥伦比亚|Colombia|Colombia|Colombia|Kolumbien|Колумбия
		CR|Costa Rica|코스타리카|コスタリカ|哥斯达黎加|Costa Rica|Costa Rica|Costa Rica|Costa Rica|Коста-Рика
		CU|Cuba|쿠바|キューバ|古巴|Cuba|Cuba|Cuba|Kuba|Куба
		CV|Cape Verde|카보베르데|カーボベルデ|佛得角|Cabo Verde|Cabo Verde|Capo Verde|Kap Verde|Кабо-Верде
		CW|Curaçao|퀴라소|キュラソー|库拉索|Curaçao|Curazao|Curaçao|Curaçao|Кюрасао
		CX|Christmas Island|크리스마스섬|クリスマス島|聖誕島|Đảo Giáng Sinh|Isla de Navidad|Isola di Natale|Weihnachtsinsel|Остров Рождества
		CY|Cyprus|키프로스|キプロス|塞浦路斯|Síp|Chipre|Cipro|Zypern|Кипр
		CZ|Czech Republic|체코|チェコ共和国|捷克|Séc|República Checa|Repubblica Ceca|Tschechien|Чехия
		DE|Germany|독일|ドイツ|德国|Đức|Alemania|Germania|Deutschland|Германия
		DJ|Djibouti|지부티|ジブチ|吉布提|Djibouti|Yibuti|Gibuti|Dschibuti|Джибути
		DK|Denmark|덴마크|デンマーク|丹麦|Đan Mạch|Dinamarca|Danimarca|Dänemark|Дания
		DM|Dominica|도미니카 연방|ドミニカ国|多米尼克|Dominica|Dominica|Dominica|Dominica|Доминика
		DO|Dominican Republic|도미니카 공화국|ドミニカ共和国|多米尼加|Cộng hòa Dominica|República Dominicana|Repubblica Dominicana|Dominikanische Republik|Доминиканская Республика
		DZ|Algeria|알제리|アルジェリア|阿尔及利亚|Algérie|Argelia|Algeria|Algerien|Алжир
		EC|Ecuador|에콰도르|エクアドル|厄瓜多尔|Ecuador|Ecuador|Ecuador|Ecuador|Эквадор
		EE|Estonia|에스토니아|エストニア|爱沙尼亚|Estonia|Estonia|Estonia|Estland|Эстония
		EG|Egypt|이집트|エジプト|埃及|Ai Cập|Egipto|Egitto|Ägypten|Египет
		EH|Western Sahara|서사하라|西サハラ|西撒哈拉|Tây Sahara|Sahara Occidental|Sahara Occidentale|Westsahara|Западная Сахара
		ER|Eritrea|에리트레아|エリトリア|厄立特里亚|Eritrea|Eritrea|Eritrea|Eritrea|Эритрея
		ES|Spain|스페인|スペイン王国|西班牙|Tây Ban Nha|España|Spagna|Spanien|Испания
		ET|Ethiopia|에티오피아|エチオピア|埃塞俄比亚|Ethiopia|Etiopía|Etiopia|Äthiopien|Эфиопия
		FI|Finland|핀란드|フィンランド|芬兰|Phần Lan|Finlandia|Finlandia|Finnland|Финляндия
		FJ|Fiji|피지|フィジー|斐济|Fiji|Fiyi|Figi|Fidschi|Фиджи
		FK|Falkland Islands|포클랜드 제도|フォークランド諸島|福克兰群岛|Quần đảo Falkland|Islas Malvinas|Isole Falkland|Falklandinseln|Фолклендские острова
		FM|Federated States of Micronesia|미크로네시아 연방|ミクロネシア連邦|密克罗尼西亚联邦|Micronesia|Estados Federados de Micronesia|Stati Federati di Micronesia|Föderierte Staaten von Mikronesien|Федеративные Штаты Микронезии
		FO|Faroe Islands|페로 제도|フェロー諸島|法罗群岛|Quần đảo Faroe|Islas Feroe|Fær Øer|Färöer|Фарерские острова
		FR|France|프랑스|フランス|法国|Pháp|Francia|Francia|Frankreich|Франция
		GA|Gabon|가봉|ガボン|加蓬|Gabon|Gabón|Gabon|Gabun|Габон
		GB|United Kingdom|영국|イギリス|英国|Vương quốc Liên hiệp Anh và Bắc Ireland|Reino Unido|Regno Unito|Vereinigtes Königreich|Великобритания
		GD|Grenada|그레나다|グレナダ|格林纳达|Grenada|Granada|Grenada|Grenada|Гренада
		GE|Georgia|조지아|ジョージア|格鲁吉亚|Gruzia|Georgia|Georgia|Georgien|Грузия
		GF|French Guiana|프랑스령 기아나|フランス領ギアナ|法属圭亚那|Guyane thuộc Pháp|Guayana Francesa|Guyana francese|Französisch-Guayana|Французская Гвиана
		GG|Guernsey|건지 행정관 관할구|ガーンジー|根西|Guernsey|Guernsey|Guernsey|Guernsey|Гернси
		GH|Ghana|가나|ガーナ|加纳|Ghana|Ghana|Ghana|Ghana|Гана
		GI|Gibraltar|지브롤터|ジブラルタル|直布罗陀|Gibraltar|Gibraltar|Gibilterra|Gibraltar|Гибралтар
		GL|Greenland|그린란드|グリーンランド|格陵兰|Greenland|Groenlandia|Groenlandia|Grönland|Гренландия
		GM|The Gambia|감비아|ガンビア|冈比亚|Gambia|Gambia|Gambia|Gambia|Гамбия
		GN|Guinea|기니|ギニア|几内亚|Guinée|Guinea|Guinea|Guinea|Гвинея
		GP|Guadeloupe|과들루프|グアドループ|瓜德罗普|Guadeloupe|Guadalupe|Guadalupa|Guadeloupe|Гваделупа
		GQ|Equatorial Guinea|적도 기니|赤道ギニア|赤道几内亚|Guinea Xích Đạo|Guinea Ecuatorial|Guinea Equatoriale|Äquatorialguinea|Экваториальная Гвинея
		GR|Greece|그리스|ギリシャ|希腊|Hy Lạp|Grecia|Grecia|Griechenland|Греция
		GS|South Georgia and the South Sandwich Islands|사우스조지아 사우스샌드위치 제도|サウスジョージア・サウスサンドウィッチ諸島|南乔治亚和南桑威奇群岛|Nam Georgia và Quần đảo Nam Sandwich|Islas Georgias del Sur y Sandwich del Sur|Georgia del Sud e isole Sandwich meridionali|Südgeorgien und die Südlichen Sandwichinseln|Южная Георгия и Южные Сандвичевы острова
		GT|Guatemala|과테말라|グアテマラ|危地马拉|Guatemala|Guatemala|Guatemala|Guatemala|Гватемала
		GU|Guam|괌|グアム|关岛|Guam|Guam|Guam|Guam|Гуам
		GW|Guinea-Bissau|기니비사우|ギニアビサウ共和国|几内亚比绍|Guiné-Bissau|Guinea-Bisáu|Guinea-Bissau|Guinea-Bissau|Гвинея-Бисау
		GY|Guyana|가이아나|ガイアナ|圭亚那|Guyana|Guyana|Guyana|Guyana|Гайана
		HK|Hong Kong|홍콩|香港|香港|Hồng Kông|Hong Kong|Hong Kong|Hongkong|Гонконг
		HM|Heard Island and McDonald Islands|허드 맥도널드 제도|ハード島とマクドナルド諸島|赫德岛和麦克唐纳群岛|Đảo Heard và quần đảo McDonald|Islas Heard y McDonald|Isole Heard e McDonald|Heard und McDonaldinseln|Остров Херд и острова Макдональд
		HN|Honduras|온두라스|ホンジュラス|洪都拉斯|Honduras|Honduras|Honduras|Honduras|Гондурас
		HR|Croatia|크로아티아|クロアチア|克罗地亚|Croatia|Croacia|Croazia|Kroatien|Хорватия
		HT|Haiti|아이티|ハイチ|海地|Haiti|Haití|Haiti|Haiti|Гаити
		HU|Hungary|헝가리|ハンガリー|匈牙利|Hungary|Hungría|Ungheria|Ungarn|Венгрия
		ID|Indonesia|인도네시아|インドネシア|印度尼西亚|Indonesia|Indonesia|Indonesia|Indonesien|Индонезия
		IE|Ireland|아일랜드|アイルランド|爱尔兰|Ireland|Irlanda|Irlanda|Irland|Ирландия
		IL|Israel|이스라엘|イスラエル|以色列|Israel|Israel|Israele|Israel|Израиль
		IM|Isle of Man|맨섬|マン島|马恩岛|Đảo Man|Isla de Man|Isola di Man|Isle of Man|Остров Мэн
		IN|India|인도|インド|印度|Ấn Độ|India|India|Indien|Индия
		IO|British Indian Ocean Territory|영국령 인도양 지역|イギリス領インド洋地域|英属印度洋领地|Lãnh thổ Ấn Độ Dương thuộc Anh|Territorio Británico del Océano Índico|Territorio Britannico dell'Oceano Indiano|Britisches Territorium im Indischen Ozean|Британская территория в Индийском океане
		IQ|Iraq|이라크|イラク|伊拉克|Iraq|Irak|Iraq|Irak|Ирак
		IR|Iran|이란|イラン|伊朗|Iran|Irán|Iran|Iran|Иран
		IS|Iceland|아이슬란드|アイスランド|冰岛|Ai-xơ-len|Islandia|Islanda|Island|Исландия
		IT|Italy|이탈리아|イタリア|意大利|Ý|Italia|Italia|Italien|Италия
		JE|Jersey|저지섬|ジャージー|泽西|Jersey|Jersey|Jersey|Jersey|Джерси
		JM|Jamaica|자메이카|ジャマイカ|牙买加|Jamaica|Jamaica|Giamaica|Jamaika|Ямайка
		JO|Jordan|요르단|ヨルダン|约旦|Jordan|Jordania|Giordania|Jordanien|Иордания
		JP|Japan|일본|日本|日本|Nhật Bản|Japón|Giappone|Japan|Япония
		KE|Kenya|케냐|ケニア|肯尼亚|Kenya|Kenia|Kenya|Kenia|Кения
		KG|Kyrgyzstan|키르기스스탄|キルギス|吉尔吉斯斯坦|Kyrgyzstan|Kirguistán|Kirghizistan|Kirgisistan|Кыргызстан
		KH|Cambodia|캄보디아|カンボジア|柬埔寨|Campuchia|Camboya|Cambogia|Kambodscha|Камбоджа
		KI|Kiribati|키리바시|キリバス|基里巴斯|Kiribati|Kiribati|Kiribati|Kiribati|Кирибати
		KM|Comoros|코모로|コモロ|科摩罗|Comoros|Comoras|Comore|Komoren|Коморы
		KN|Saint Kitts and Nevis|세인트키츠 네비스|セントクリストファー・ネイビス|圣基茨和尼维斯|Saint Kitts và Nevis|San Cristóbal y Nieves|Saint Kitts e Nevis|St. Kitts und Nevis|Сент-Китс и Невис
		KP|North Korea|조선민주주의인민공화국|朝鮮民主主義人民共和国|朝鲜民主主义人民共和国|Cộng hòa Dân chủ Nhân dân Triều Tiên|Corea del Norte|Corea del Nord|Nordkorea|КНДР
		KR|South Korea|대한민국|大韓民国|大韩民国|Hàn Quốc|Corea del Sur|Corea del Sud|Südkorea|Республика Корея
		KW|Kuwait|쿠웨이트|クウェート|科威特|Kuwait|Kuwait|Kuwait|Kuwait|Кувейт
		KY|Cayman Islands|케이맨 제도|ケイマン諸島|开曼群岛|Quần đảo Cayman|Islas Caimán|Isole Cayman|Cayman Islands|Каймановы Острова
		KZ|Kazakhstan|카자흐스탄|カザフスタン|哈萨克斯坦|Kazakhstan|Kazajistán|Kazakistan|Kasachstan|Казахстан
		LA|Laos|라오스|ラオス|老挝|Lào|Laos|Laos|Laos|Лаос
		LB|Lebanon|레바논|レバノン|黎巴嫩|Liban|Líbano|Libano|Libanon|Ливан
		LC|Saint Lucia|세인트루시아|セントルシア|圣卢西亚|Saint Lucia|Santa Lucía|Saint Lucia|St. Lucia|Сент-Люсия
		LI|Liechtenstein|리히텐슈타인|リヒテンシュタイン|列支敦士登|Liechtenstein|Liechtenstein|Liechtenstein|Liechtenstein|Лихтенштейн
		LK|Sri Lanka|스리랑카|スリランカ|斯里兰卡|Sri Lanka|Sri Lanka|Sri Lanka|Sri Lanka|Шри-Ланка
		LR|Liberia|라이베리아|リベリア|利比里亚|Liberia|Liberia|Liberia|Liberia|Либерия
		LS|Lesotho|레소토|レソト|莱索托|Lesotho|Lesoto|Lesotho|Lesotho|Лесото
		LT|Lithuania|리투아니아|リトアニア|立陶宛|Litva|Lituania|Lituania|Litauen|Литва
		LU|Luxembourg|룩셈부르크|ルクセンブルク|卢森堡|Luxembourg|Luxemburgo|Lussemburgo|Luxemburg|Люксембург
		LV|Latvia|라트비아|ラトビア|拉脱维亚|Latvia|Letonia|Lettonia|Lettland|Латвия
		LY|Libya|리비아|リビア|利比亚|Libya|Libia|Libia|Libyen|Ливия
		MA|Morocco|모로코|モロッコ|摩洛哥|Maroc|Marruecos|Marocco|Marokko|Марокко
		MC|Monaco|모나코|モナコ|摩纳哥|Monaco|Mónaco|Principato di Monaco|Monaco|Монако
		MD|Moldova|몰도바|モルドバ|摩尔多瓦|Moldova|Moldavia|Moldavia|Moldau|Молдова
		ME|Montenegro|몬테네그로|モンテネグロ|黑山|Montenegro|Montenegro|Montenegro|Montenegro|Черногория
		MF|Saint-Martin|생마르탱|サン・マルタン|法属圣马丁|Saint-Martin|San Martín|Saint-Martin|Saint-Martin|Сен-Мартен
		MG|Madagascar|마다가스카르|マダガスカル|马达加斯加|Madagascar|Madagascar|Madagascar|Madagaskar|Мадагаскар
		MH|Marshall Islands|마셜 제도|マーシャル諸島|马绍尔群岛|Quần đảo Marshall|Islas Marshall|Isole Marshall|Marshallinseln|Маршалловы Острова
		MK|North Macedonia|북마케도니아|北マケドニア|北马其顿|Bắc Macedonia|Macedonia del Norte|Macedonia del Nord|Nordmazedonien|Северная Македония
		ML|Mali|말리|マリ共和国|马里|Mali|Mali|Mali|Mali|Мали
		MM|Myanmar|미얀마|ミャンマー|缅甸|Myanma|Birmania|Myanmar|Myanmar|Мьянма
		MN|Mongolia|몽골|モンゴル国|蒙古国|Mông Cổ|Mongolia|Mongolia|Mongolei|Монголия
		MO|Macau|마카오|マカオ|澳门|Ma Cao|Macao|Macao|Macau|Макао
		MP|Northern Mariana Islands|북마리아나 제도|北マリアナ諸島|北马里亚纳群岛|Quần đảo Bắc Mariana|Islas Marianas del Norte|Isole Marianne Settentrionali|Nördliche Marianen|Северные Марианские Острова
		MQ|Martinique|마르티니크|マルティニーク|马提尼克|Martinique|Martinica|Martinica|Martinique|Мартиника
		MR|Mauritania|모리타니|モーリタニア|毛里塔尼亚|Mauritanie|Mauritania|Mauritania|Mauretanien|Мавритания
		MS|Montserrat|몬트세랫|モントセラト|蒙特塞拉特|Montserrat|Montserrat|Montserrat|Montserrat|Монтсеррат
		MT|Malta|몰타|マルタ|马耳他|Malta|Malta|Malta|Malta|Мальта
		MU|Mauritius|모리셔스|モーリシャス|毛里求斯|Mauritius|Mauricio|Mauritius|Mauritius|Маврикий
		MV|Maldives|몰디브|モルディブ|马尔代夫|Maldives|Maldivas|Maldive|Malediven|Мальдивы
		MW|Malawi|말라위|マラウイ|马拉维|Malawi|Malaui|Malawi|Malawi|Малави
		MX|Mexico|멕시코|メキシコ|墨西哥|México|México|Messico|Mexiko|Мексика
		MY|Malaysia|말레이시아|マレーシア|马来西亚|Malaysia|Malasia|Malaysia|Malaysia|Малайзия
		MZ|Mozambique|모잠비크|モザンビーク|莫桑比克|Mozambique|Mozambique|Mozambico|Mosambik|Мозамбик
		NA|Namibia|나미비아|ナミビア|纳米比亚|Namibia|Namibia|Namibia|Namibia|Намибия
		NC|New Caledonia|누벨칼레도니|ニューカレドニア|新喀里多尼亚|Nouvelle-Calédonie|Nueva Caledonia|Nuova Caledonia|Neukaledonien|Новая Каледония
		NE|Niger|니제르|ニジェール|尼日尔|Niger|Níger|Niger|Niger|Нигер
		NF|Norfolk Island|노퍽섬|ノーフォーク島|诺福克岛|Đảo Norfolk|Isla Norfolk|Isola Norfolk|Norfolkinsel|Норфолк
		NG|Nigeria|나이지리아|ナイジェリア|尼日利亚|Nigeria|Nigeria|Nigeria|Nigeria|Нигерия
		NI|Nicaragua|니카라과|ニカラグア|尼加拉瓜|Nicaragua|Nicaragua|Nicaragua|Nicaragua|Никарагуа
		NL|Netherlands|네덜란드|オランダ|荷兰|Hà Lan|Países Bajos|Paesi Bassi|Niederlande|Нидерланды
		NO|Norway|노르웨이|ノルウェー王国|挪威|Na Uy|Noruega|Norvegia|Norwegen|Норвегия
		NP|Nepal|네팔|ネパール|尼泊尔|Nepal|Nepal|Nepal|Nepal|Непал
		NR|Nauru|나우루|ナウル|瑙鲁|Nauru|Nauru|Nauru|Naoero|Науру
		NU|Niue|니우에|ニウエ|纽埃|Niue|Niue|Niue|Niue|Ниуэ
		NZ|New Zealand|뉴질랜드|ニュージーランド|新西兰|New Zealand|Nueva Zelanda|Nuova Zelanda|Neuseeland|Новая Зеландия
		OM|Oman|오만|オマーン|阿曼|Oman|Omán|Oman|Oman|Оман
		PA|Panama|파나마|パナマ|巴拿马|Panama|Panamá|Panama|Panama|Панама
		PE|Peru|페루|ペルー|秘鲁|Perú|Perú|Perù|Peru|Перу
		PF|French Polynesia|프랑스령 폴리네시아|フランス領ポリネシア|法属波利尼西亚|Polynésie thuộc Pháp|Polinesia Francesa|Polinesia francese|Französisch-Polynesien|Французская Полинезия
		PG|Papua New Guinea|파푸아뉴기니|パプアニューギニア|巴布亚新几内亚|Papua New Guinea|Papúa Nueva Guinea|Papua Nuova Guinea|Papua-Neuguinea|Папуа — Новая Гвинея
		PH|Philippines|필리핀|フィリピン|菲律宾|Philippines|Filipinas|Filippine|Philippinen|Филиппины
		PK|Pakistan|파키스탄|パキスタン|巴基斯坦|Pakistan|Pakistán|Pakistan|Pakistan|Пакистан
		PL|Poland|폴란드|ポーランド|波兰|Ba Lan|Polonia|Polonia|Polen|Польша
		PM|Saint Pierre and Miquelon|생피에르 미클롱|サンピエール島・ミクロン島|圣皮埃尔和密克隆|Saint-Pierre và Miquelon|San Pedro y Miquelón|Saint-Pierre e Miquelon|Saint-Pierre und Miquelon|Сен-Пьер и Микелон
		PN|Pitcairn Islands|핏케언 제도|ピトケアン諸島|皮特凯恩群岛|Quần đảo Pitcairn|Islas Pitcairn|Isole Pitcairn|Pitcairninseln|Острова Питкэрн
		PR|Puerto Rico|푸에르토리코|プエルトリコ|波多黎各|Puerto Rico|Puerto Rico|Porto Rico|Puerto Rico|Пуэрто-Рико
		PS|Palestine|팔레스타인|パレスチナ国|巴勒斯坦|Nhà nước Palestine|Palestina|Stato di Palestina|Palästina|Государство Палестина
		PT|Portugal|포르투갈|ポルトガル|葡萄牙|Bồ Đào Nha|Portugal|Portogallo|Portugal|Португалия
		PW|Palau|팔라우|パラオ|帕劳|Palau|Palaos|Palau|Palau|Палау
		PY|Paraguay|파라과이|パラグアイ|巴拉圭|Paraguay|Paraguay|Paraguay|Paraguay|Парагвай
		QA|Qatar|카타르|カタール|卡塔尔|Qatar|Catar|Qatar|Katar|Катар
		RE|Réunion|레위니옹|レユニオン|留尼汪|Réunion|Reunión|Riunione|Réunion|Реюньон
		RO|Romania|루마니아|ルーマニア|罗马尼亚|România|Rumania|Romania|Rumänien|Румыния
		RS|Serbia|세르비아|セルビア|塞尔维亚|Serbia|Serbia|Serbia|Serbien|Сербия
		RU|Russia|러시아|ロシア|俄罗斯|Nga|Rusia|Russia|Russland|Россия
		RW|Rwanda|르완다|ルワンダ|卢旺达|Rwanda|Ruanda|Ruanda|Ruanda|Руанда
		SA|Saudi Arabia|사우디아라비아|サウジアラビア|沙特阿拉伯|Ả Rập Xê Út|Arabia Saudí|Arabia Saudita|Saudi-Arabien|Саудовская Аравия
		SB|Solomon Islands|솔로몬 제도|ソロモン諸島|所罗门群岛|Quần đảo Solomon|Islas Salomón|Isole Salomone|Salomonen|Соломоновы Острова
		SC|Seychelles|세이셸|セーシェル|塞舌尔|Seychelles|Seychelles|Seychelles|Seychellen|Сейшельские Острова
		SD|Sudan|수단|スーダン|苏丹|Sudan|Sudán|Sudan|Sudan|Судан
		SE|Sweden|스웨덴|スウェーデン|瑞典|Thụy Điển|Suecia|Svezia|Schweden|Швеция
		SG|Singapore|싱가포르|シンガポール|新加坡|Singapore|Singapur|Singapore|Singapur|Сингапур
		SH|Saint Helena, Ascension and Tristan da Cunha|세인트헬레나 어센션 트리스탄다쿠냐|セントヘレナ・アセンションおよびトリスタンダクーニャ|圣赫勒拿、阿森松和特里斯坦-达库尼亚|Saint Helena, Ascension và Tristan da Cunha|Santa Elena, Ascensión y Tristán de Acuña|Sant'Elena, Ascensione e Tristan da Cunha|St. Helena, Ascension und Tristan da Cunha|Острова Святой Елены, Вознесения и Тристан-да-Кунья
		SI|Slovenia|슬로베니아|スロベニア|斯洛文尼亚|Slovenia|Eslovenia|Slovenia|Slowenien|Словения
		SJ|Svalbard and Jan Mayen|스발바르 얀마옌 제도|スヴァールバル諸島およびヤンマイエン島|斯瓦尔巴和扬马延|Svalbard và Jan Mayen|Svalbard y Jan Mayen|Svalbard e Jan Mayen|Svalbard und Jan Mayen|Шпицберген и Ян-Майен
		SK|Slovakia|슬로바키아|スロバキア|斯洛伐克|Slovakia|Eslovaquia|Slovacchia|Slowakei|Словакия
		SL|Sierra Leone|시에라리온|シエラレオネ|塞拉利昂|Sierra Leone|Sierra Leona|Sierra Leone|Sierra Leone|Сьерра-Леоне
		SM|San Marino|산마리노|サンマリノ|圣马力诺|San Marino|San Marino|San Marino|San Marino|Сан-Марино
		SN|Senegal|세네갈|セネガル|塞内加尔|Sénégal|Senegal|Senegal|Senegal|Сенегал
		SO|Somalia|소말리아|ソマリア|索马里|Somalia|Somalia|Somalia|Somalia|Сомали
		SR|Suriname|수리남|スリナム|苏里南|Suriname|Surinam|Suriname|Suriname|Суринам
		SS|South Sudan|남수단|南スーダン|南苏丹|Nam Sudan|Sudán del Sur|Sudan del Sud|Südsudan|Южный Судан
		ST|São Tomé and Príncipe|상투메 프린시페|サントメ・プリンシペ|圣多美和普林西比|São Tomé và Príncipe|Santo Tomé y Príncipe|São Tomé e Príncipe|São Tomé und Príncipe|Сан-Томе и Принсипи
		SV|El Salvador|엘살바도르|エルサルバドル|萨尔瓦多|El Salvador|El Salvador|El Salvador|El Salvador|Сальвадор
		SX|Sint Maarten|신트마르턴|シント・マールテン|荷属圣马丁|Sint Maarten|San Martín|Sint Maarten|Sint Maarten|Синт-Мартен
		SY|Syria|시리아|シリア|叙利亚|Syria|Siria|Siria|Syrien|Сирия
		SZ|Eswatini|에스와티니|エスワティニ|斯威士兰|Eswatini|Suazilandia|Eswatini|Eswatini|Эсватини
		TC|Turks and Caicos Islands|터크스 케이커스 제도|タークス・カイコス諸島|特克斯和凯科斯群岛|Quần đảo Turks và Caicos|Islas Turcas y Caicos|Turks e Caicos|Turks- und Caicosinseln|Тёркс и Кайкос
		TD|Chad|차드|チャド|乍得|Tchad|Chad|Ciad|Tschad|Чад
		TF|French Southern and Antarctic Lands|프랑스령 남방 및 남극 지역|フランス領南方・南極地域|法属南部和南极领地|Vùng đất phía Nam và châu Nam Cực thuộc Pháp|Tierras Australes y Antárticas Francesas|Terre Australi e Antartiche Francesi|Französische Süd- und Antarktisgebiete|Французские Южные и Антарктические территории
		TG|Togo|토고|トーゴ|多哥|Togo|Togo|Togo|Togo|Того
		TH|Thailand|태국|タイ王国|泰国|Thái Lan|Tailandia|Tailandia|Thailand|Таиланд
		TJ|Tajikistan|타지키스탄|タジキスタン|塔吉克斯坦|Tajikistan|Tayikistán|Tagikistan|Tadschikistan|Таджикистан
		TK|Tokelau|토켈라우|トケラウ|托克劳|Tokelau|Tokelau|Tokelau|Tokelau|Токелау
		TL|Timor-Leste|동티모르|東ティモール|东帝汶|Đông Timor|Timor Oriental|Timor Est|Osttimor|Восточный Тимор
		TM|Turkmenistan|투르크메니스탄|トルクメニスタン|土库曼斯坦|Turkmenistan|Turkmenistán|Turkmenistan|Turkmenistan|Туркменистан
		TN|Tunisia|튀니지|チュニジア|突尼斯|Tunisia|Túnez|Tunisia|Tunesien|Тунис
		TO|Tonga|통가|トンガ|汤加|Tonga|Tonga|Tonga|Tonga|Тонга
		TR|Turkey|튀르키예|トルコ|土耳其|Thổ Nhĩ Kỳ|Turquía|Turchia|Türkei|Турция
		TT|Trinidad and Tobago|트리니다드 토바고|トリニダード・トバゴ|特立尼达和多巴哥|Trinidad và Tobago|Trinidad y Tobago|Trinidad e Tobago|Trinidad und Tobago|Тринидад и Тобаго
		TV|Tuvalu|투발루|ツバル|图瓦卢|Tuvalu|Tuvalu|Tuvalu|Tuvalu|Тувалу
		TW|Taiwan|중화민국|中華民国|中华民国|Đài Loan|República de China|Taiwan|Taiwan|Китайская Республика (Тайвань)
		TZ|Tanzania|탄자니아|タンザニア|坦桑尼亚|Tanzania|Tanzania|Tanzania|Tansania|Танзания
		UA|Ukraine|우크라이나|ウクライナ|乌克兰|Ukraina|Ucrania|Ucraina|Ukraine|Украина
		UG|Uganda|우간다|ウガンダ|乌干达|Uganda|Uganda|Uganda|Uganda|Уганда
		UM|United States Minor Outlying Islands|미국령 군소 제도|合衆国領有小離島|美国本土外小岛屿|Các tiểu đảo xa của Hoa Kỳ|Islas ultramarinas de Estados Unidos|Isole minori esterne degli Stati Uniti d'America|Kleinere Amerikanische Überseeinseln|Внешние малые острова США
		US|United States|미국|アメリカ合衆国|美国|Hoa Kỳ|Estados Unidos|Stati Uniti|Vereinigte Staaten|США
		UY|Uruguay|우루과이|ウルグアイ|乌拉圭|Uruguay|Uruguay|Uruguay|Uruguay|Уругвай
		UZ|Uzbekistan|우즈베키스탄|ウズベキスタン|乌兹别克斯坦|Uzbekistan|Uzbekistán|Uzbekistan|Usbekistan|Узбекистан
		VA|Vatican City|바티칸 시국|バチカン|梵蒂冈|Thành Vatican|Ciudad del Vaticano|Città del Vaticano|Vatikanstadt|Ватикан
		VC|Saint Vincent and the Grenadines|세인트빈센트 그레나딘|セントビンセント・グレナディーン|圣文森特和格林纳丁斯|Saint Vincent và Grenadines|San Vicente y las Granadinas|Saint Vincent e Grenadine|St. Vincent und die Grenadinen|Сент-Винсент и Гренадины
		VE|Venezuela|베네수엘라|ベネズエラ|委内瑞拉|Venezuela|Venezuela|Venezuela|Venezuela|Венесуэла
		VG|British Virgin Islands|영국령 버진아일랜드|イギリス領ヴァージン諸島|英属维尔京群岛|Quần đảo Virgin thuộc Anh|Islas Vírgenes Británicas|Isole Vergini Britanniche|Britische Jungferninseln|Британские Виргинские Острова
		VI|United States Virgin Islands|미국령 버진아일랜드|アメリカ領ヴァージン諸島|美属维尔京群岛|Quần đảo Virgin thuộc Mỹ|Islas Vírgenes de los Estados Unidos|Isole Vergini degli Stati Uniti|Amerikanische Jungferninseln|Американские Виргинские Острова
		VN|Vietnam|베트남|ベトナム|越南|Việt Nam|Vietnam|Vietnam|Vietnam|Вьетнам
		VU|Vanuatu|바누아투|バヌアツ|瓦努阿图|Vanuatu|Vanuatu|Vanuatu|Vanuatu|Вануату
		WF|Wallis and Futuna|왈리스 푸투나|ウォリス・フツナ|瓦利斯和富图纳|Wallis và Futuna|Wallis y Futuna|Wallis e Futuna|Wallis und Futuna|Уоллис и Футуна
		WS|Samoa|사모아|サモア|萨摩亚|Samoa|Samoa|Samoa|Samoa|Самоа
		YE|Yemen|예멘|イエメン|也门|Yemen|Yemen|Yemen|Jemen|Йемен
		YT|Mayotte|마요트|マヨット|马约特|Mayotte|Mayotte|Mayotte|Mayotte|Майотта
		ZA|South Africa|남아프리카 공화국|南アフリカ共和国|南非|Nam Phi|Sudáfrica|Sudafrica|Südafrika|ЮАР
		ZM|Zambia|잠비아|ザンビア|赞比亚|Zambia|Zambia|Zambia|Sambia|Замбия
		ZW|Zimbabwe|짐바브웨|ジンバブエ|津巴布韦|Zimbabwe|Zimbabue|Zimbabwe|Simbabwe|Зимбабве
	`
};
