"""randino — names, nicknames, words, sentences, places, ages, dates and phone numbers.

Separate concerns, deliberately. `rand_name` produces names a person could actually
carry (`김민준`, `Emma Clover`); `rand_nickname` produces the handle someone would pick
for a game or a website (`멋진사자`, `MistyOwl`), built from everyday words and never
from person names; `rand_word` hands those words over on their own; `rand_sentence`
writes a whole statement in the language's own grammar; `rand_location` writes a real
place, from the country down to a Korean 읍·면·동 or a US city; `rand_age` draws an age
along a curve shaped like a population; `rand_gender` writes the label a form in the
language uses for a gender; `rand_organization` names a company, a school or an office
that does not exist; `rand_date` draws a date from a range and writes it out by a format,
or hands back one part of it; and `rand_phone` writes a phone number the way its country
does.

Example:
    >>> from randino import rand_name, rand_nickname, rand_sentence
    >>> rand_name(language="ko", count=3)
    ['김민준', '이서연', '박지호']
    >>> rand_nickname(language="en")
    ['MistyOwl']
    >>> rand_sentence(language="en")
    ['The brave lion runs quietly.']
"""

from randino._types import (
    AgeDetail,
    AgeDistribution,
    AgeGroup,
    AgeGroupOption,
    Architecture,
    ArchitectureDetail,
    CountryDetail,
    CpuDetail,
    DateDetail,
    DateInput,
    DateUnit,
    DeviceDetail,
    DeviceType,
    DeviceTypeOption,
    DiskSizeDetail,
    DiskType,
    DiskTypeDetail,
    DiskUnit,
    DiskUnitOption,
    GenderCode,
    GenderDetail,
    GpuDetail,
    LocationDetail,
    LocationLanguage,
    LocationLanguageOption,
    LocationLevel,
    ModifierKind,
    NameDetail,
    NameGender,
    NameGenderOption,
    NameLanguage,
    NameLanguageOption,
    NameScript,
    NicknameDetail,
    OrganizationDetail,
    OrganizationIndustry,
    OrganizationIndustryOption,
    OrganizationType,
    OrganizationTypeOption,
    OsDetail,
    PhoneCountry,
    PhoneCountryOption,
    PhoneDetail,
    PhoneType,
    PhoneTypeOption,
    RamDetail,
    RamUnit,
    RamUnitOption,
    RandRealism,
    RandVocabulary,
    ResolutionDetail,
    SentenceDetail,
    SentenceQuote,
    SentenceShape,
    SentenceShapeOption,
    SentenceSlot,
    SentenceSlotOption,
    SentenceStory,
    SentenceStyle,
    SentenceTense,
    SentenceType,
    SentenceTypeOption,
    SystemPlatform,
    SystemPlatformOption,
    VersionDetail,
    VersionFormat,
    VersionFormatOption,
    WordDetail,
    WordLanguage,
    WordLanguageOption,
    WordSlot,
    WordSlotOption,
    WordTheme,
    WordThemeOption,
)
from randino.age import AGE_GROUPS, rand_age
from randino.architecture import ARCHITECTURES, rand_architecture
from randino.constants import (
    RAND_AGE_MAX,
    RAND_COUNT_MAX,
    RAND_LENGTH_MAX,
    RAND_LENGTH_MIN,
    RAND_LOCATION_LENGTH_MAX,
    RAND_ORGANIZATION_LENGTH_MAX,
    RAND_SENTENCE_COUNT_MAX,
    RAND_SENTENCE_LENGTH_MAX,
    SYSTEM_PLATFORMS,
)
from randino.cpu import rand_cpu
from randino.date import DATE_UNITS, rand_date
from randino.decorate import (
    AFFIX_CHARSET,
    AFFIX_LENGTH_DEFAULT,
    AFFIX_LENGTH_MAX,
    AFFIX_SEPARATOR_DEFAULT,
    rand_modifier,
    rand_prefix,
    rand_suffix,
)
from randino.device import DEVICE_TYPES, rand_device
from randino.disk import DISK_TYPES, DISK_UNITS, rand_disk_size, rand_disk_type
from randino.gender import rand_gender
from randino.gpu import rand_gpu
from randino.location import (
    LOCATION_LANGUAGES,
    LOCATION_LEVELS,
    rand_city,
    rand_country,
    rand_district,
    rand_location,
    rand_region,
)
from randino.name import (
    NAME_LANGUAGES,
    name_length_range,
    name_supports_middle_name,
    name_supports_roman,
    rand_name,
)
from randino.nickname import nickname_length_range, rand_nickname
from randino.organization import ORGANIZATION_INDUSTRIES, ORGANIZATION_TYPES, rand_organization
from randino.os import rand_os
from randino.phone import PHONE_COUNTRIES, PHONE_TYPES, rand_phone
from randino.ram import RAM_UNITS, rand_ram
from randino.resolution import rand_resolution
from randino.sentence import rand_sentence, sentence_length_range
from randino.version import VERSION_FORMATS, rand_version
from randino.word import (
    WORD_LANGUAGES,
    WORD_THEMES,
    rand_animal,
    rand_body,
    rand_clothing,
    rand_color,
    rand_concept,
    rand_drink,
    rand_emotion,
    rand_finance,
    rand_food,
    rand_furniture,
    rand_gem,
    rand_job,
    rand_music,
    rand_myth,
    rand_nature,
    rand_object,
    rand_person,
    rand_place,
    rand_plant,
    rand_product,
    rand_sound,
    rand_space,
    rand_sport,
    rand_tech,
    rand_time,
    rand_tool,
    rand_toy,
    rand_vehicle,
    rand_weather,
    rand_word,
    word_length_range,
)

__all__ = [
    "AFFIX_CHARSET",
    "AFFIX_LENGTH_DEFAULT",
    "AFFIX_LENGTH_MAX",
    "AFFIX_SEPARATOR_DEFAULT",
    "AGE_GROUPS",
    "ARCHITECTURES",
    "DATE_UNITS",
    "DEVICE_TYPES",
    "DISK_TYPES",
    "DISK_UNITS",
    "LOCATION_LANGUAGES",
    "LOCATION_LEVELS",
    "NAME_LANGUAGES",
    "ORGANIZATION_INDUSTRIES",
    "ORGANIZATION_TYPES",
    "PHONE_COUNTRIES",
    "PHONE_TYPES",
    "RAM_UNITS",
    "RAND_AGE_MAX",
    "RAND_COUNT_MAX",
    "RAND_LENGTH_MAX",
    "RAND_LENGTH_MIN",
    "RAND_LOCATION_LENGTH_MAX",
    "RAND_ORGANIZATION_LENGTH_MAX",
    "RAND_SENTENCE_COUNT_MAX",
    "RAND_SENTENCE_LENGTH_MAX",
    "SYSTEM_PLATFORMS",
    "VERSION_FORMATS",
    "WORD_LANGUAGES",
    "WORD_THEMES",
    "AgeDetail",
    "AgeDistribution",
    "AgeGroup",
    "AgeGroupOption",
    "Architecture",
    "ArchitectureDetail",
    "CountryDetail",
    "CpuDetail",
    "DateDetail",
    "DateInput",
    "DateUnit",
    "DeviceDetail",
    "DeviceType",
    "DeviceTypeOption",
    "DiskSizeDetail",
    "DiskType",
    "DiskTypeDetail",
    "DiskUnit",
    "DiskUnitOption",
    "GenderCode",
    "GenderDetail",
    "GpuDetail",
    "LocationDetail",
    "LocationLanguage",
    "LocationLanguageOption",
    "LocationLevel",
    "ModifierKind",
    "NameDetail",
    "NameGender",
    "NameGenderOption",
    "NameLanguage",
    "NameLanguageOption",
    "NameScript",
    "NicknameDetail",
    "OrganizationDetail",
    "OrganizationIndustry",
    "OrganizationIndustryOption",
    "OrganizationType",
    "OrganizationTypeOption",
    "OsDetail",
    "PhoneCountry",
    "PhoneCountryOption",
    "PhoneDetail",
    "PhoneType",
    "PhoneTypeOption",
    "RamDetail",
    "RamUnit",
    "RamUnitOption",
    "RandRealism",
    "RandVocabulary",
    "ResolutionDetail",
    "SentenceDetail",
    "SentenceQuote",
    "SentenceShape",
    "SentenceShapeOption",
    "SentenceSlot",
    "SentenceSlotOption",
    "SentenceStory",
    "SentenceStyle",
    "SentenceTense",
    "SentenceType",
    "SentenceTypeOption",
    "SystemPlatform",
    "SystemPlatformOption",
    "VersionDetail",
    "VersionFormat",
    "VersionFormatOption",
    "WordDetail",
    "WordLanguage",
    "WordLanguageOption",
    "WordSlot",
    "WordSlotOption",
    "WordTheme",
    "WordThemeOption",
    "name_length_range",
    "name_supports_middle_name",
    "name_supports_roman",
    "nickname_length_range",
    "rand_age",
    "rand_animal",
    "rand_architecture",
    "rand_body",
    "rand_city",
    "rand_clothing",
    "rand_color",
    "rand_concept",
    "rand_country",
    "rand_cpu",
    "rand_date",
    "rand_device",
    "rand_disk_size",
    "rand_disk_type",
    "rand_district",
    "rand_drink",
    "rand_emotion",
    "rand_finance",
    "rand_food",
    "rand_furniture",
    "rand_gem",
    "rand_gender",
    "rand_gpu",
    "rand_job",
    "rand_location",
    "rand_modifier",
    "rand_music",
    "rand_myth",
    "rand_name",
    "rand_nature",
    "rand_nickname",
    "rand_object",
    "rand_organization",
    "rand_os",
    "rand_person",
    "rand_phone",
    "rand_place",
    "rand_plant",
    "rand_prefix",
    "rand_product",
    "rand_ram",
    "rand_region",
    "rand_resolution",
    "rand_sentence",
    "rand_sound",
    "rand_space",
    "rand_sport",
    "rand_suffix",
    "rand_tech",
    "rand_time",
    "rand_tool",
    "rand_toy",
    "rand_vehicle",
    "rand_version",
    "rand_weather",
    "rand_word",
    "sentence_length_range",
    "word_length_range",
]
